import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as colors
import matplotlib.ticker as ticker
import os
import torch
# import matplotlib.patches as patches  # Add this import at the top

# ==========================================
# 1. CONFIGURATION & FILE PATHS
# ==========================================
# Update these paths to match your local environment
checkpoint_path = '/dat/andreuva/gpu/graphnet/graphnet_nlte/checkpoints/multistride_cpudtst_4x4_s4_m8_b8_r6_d025_press/2026.03.01-02:16:27_best.pth'

dataset_size = 'full'
stride = 3
highlight_map = [None, 1, 1, 1, 1, 1, 3]
highlight_color = '#b603fc' #'#00FF00' # Bright Green

# Replace with the actual paths generated by your inference script
predictions_path = f'/dat/andreuva/gpu/graphnet/graphnet_nlte/checkpoints/multistride_cpudtst_4x4_s4_m8_b8_r6_d025_press/predictions_patch_stride_{stride}_{dataset_size}.npy'
targets_path = f'/dat/andreuva/gpu/graphnet/graphnet_nlte/checkpoints/multistride_cpudtst_4x4_s4_m8_b8_r6_d025_press/targets_patch_stride_{stride}_{dataset_size}.npy'
savedir = f'/dat/andreuva/gpu/graphnet/graphnet_nlte/checkpoints/multistride_cpudtst_4x4_s4_m8_b8_r6_d025_press/' # Directory where plots will be saved

# os.makedirs(savedir, exist_ok=True)

# Configure matplotlib for paper-quality plots
plt.rcParams.update({
    'font.size': 12, 'axes.titlesize': 12, 'axes.labelsize': 11,
    'xtick.labelsize': 10, 'ytick.labelsize': 10, 'legend.fontsize': 10,
    'figure.titlesize': 14
})

# ==========================================
# 2. LOAD DATA AND RECONSTRUCT GRID
# ==========================================
print(f"Loading saved populations, s={stride}, {dataset_size}...")
predictions_denorm = np.load(predictions_path)
targets_denorm = np.load(targets_path)

new_nz, ny_size, nx_size, nlev = targets_denorm.shape
print(f"Loaded spatial cubes of shape: {targets_denorm.shape}")

print("Reconstructing geometry grid from checkpoint config...")
checkpoint = torch.load(checkpoint_path, map_location='cpu', weights_only=False)
config = checkpoint['config']
nz = config['data']['nz_orig']
nz_linear = config['dataset']['nz_linear']
nz_log = config['dataset']['nz_log']
logspace_fraction = config['dataset']['logspace_fraction']

z = np.arange(nz)
new_z_log = np.concatenate([
    np.linspace(0, nz * logspace_fraction, nz_linear, endpoint=False),
    np.logspace(np.log10(nz * logspace_fraction), np.log10(nz - 1), nz_log)
])
new_z = np.clip(new_z_log, 0, nz - 1)
geometry_grid = np.load(config["data"]["grid_file"])["z"]
zz_grid = np.interp(new_z, z, geometry_grid)

# ==========================================
# 3. DATA FLATTENING & FILTERING
# ==========================================
print("Flattening data and filtering out padded background...")
# Reshape to (pixels, nlev)
predictions_denorm_flat_all = predictions_denorm.reshape(-1, nlev)
targets_denorm_flat_all = targets_denorm.reshape(-1, nlev)

# Create corresponding z-indices for each pixel
z_indices = np.arange(new_nz).reshape(new_nz, 1, 1).repeat(ny_size, axis=1).repeat(nx_size, axis=2)
z_indices_flat_all = z_indices.flatten()

# Filter out zero-padding (pixels where target is 0)
valid_pixels = targets_denorm_flat_all[:, 0] > 0

predictions_denorm_flat = predictions_denorm_flat_all[valid_pixels]
targets_denorm_flat = targets_denorm_flat_all[valid_pixels]
z_indices_flat = z_indices_flat_all[valid_pixels]
z_grid_flat = zz_grid[z_indices_flat]

# Calculate errors
residuals_denorm = (predictions_denorm_flat - targets_denorm_flat) / (targets_denorm_flat + 1e-12)
mae_denorm = np.mean(np.abs(residuals_denorm), axis=0)
rmse_denorm = np.sqrt(np.mean(residuals_denorm**2, axis=0))

print("Data preparation complete. Generating plots...")

# ==========================================
# PLOT 1: SPATIAL ERROR MAPS
# ==========================================
print("Generating Plot 1: Spatial Inference Maps...")
z_slices = [6, 20, 35, 45]   
cols = len(z_slices)
rows = nlev + 1          

# Ensure the list is long enough for your rows, or default to None if out of bounds
def get_highlight_col(row_idx):
    if row_idx < len(highlight_map):
        return highlight_map[row_idx]
    return None

fig, axes = plt.subplots(rows, cols, figsize=(10, 18), dpi=150,
                         constrained_layout=True, gridspec_kw={'wspace': 0, 'hspace': 0})

for r in range(rows): 
    for col_idx, z_idx in enumerate(z_slices): 
        ax = axes[r, col_idx]
        
        if r == 0:
            targ_panel = targets_denorm[z_idx, :, :, 0]
            # Handle zeroes for log space in empty padding regions
            targ_panel_safe = np.where(targ_panel > 0, targ_panel, np.nan)
            im_targ = ax.imshow(np.log10(targ_panel_safe), cmap='magma', origin='lower')
            
            if col_idx == 0:
                ax.set_ylabel(r"$n_{Ca_{II}}\ (i=0)$", fontsize=18, fontweight='bold')
            
            cbar = fig.colorbar(im_targ, ax=ax, location='top', fraction=0.05, pad=0.02)
            cbar.set_label(r'$log_{10}(\ n ($' + f'z={zz_grid[z_idx]:1.1f} Mm))', fontsize=16)
            cbar.ax.xaxis.set_ticks_position('top')
            cbar.ax.xaxis.set_label_position('top')
            cbar.ax.tick_params(labelsize=12)
            cbar.locator = ticker.MaxNLocator(nbins=5)
            cbar.update_ticks()

        else:
            lvl = r - 1
            pred_panel = predictions_denorm[z_idx, :, :, lvl]
            targ_panel = targets_denorm[z_idx, :, :, lvl]
            
            with np.errstate(divide='ignore', invalid='ignore'):
                diff = np.log10(pred_panel) - np.log10(targ_panel)
                diff_vol_at_z = np.log10(predictions_denorm[z_idx, :, :, :]) - np.log10(targets_denorm[z_idx, :, :, :])
            
            diff_vol_at_z = diff_vol_at_z[~np.isnan(diff_vol_at_z) & ~np.isinf(diff_vol_at_z)]
            vmax = np.percentile(np.abs(diff_vol_at_z), 92) if len(diff_vol_at_z) > 0 else 1.0
            vmin = -vmax
            
            im_err = ax.imshow(diff, cmap='RdBu_r', vmin=vmin, vmax=vmax, origin='lower')
            
            if r == rows - 1 and col_idx == 0:
                ax.set_ylabel(r"$\epsilon_{Ca_{III}}$", fontsize=18)
            elif col_idx == 0:
                ax.set_ylabel(r"$\epsilon_{Ca_{II}}$" + f" (i={lvl})", fontsize=18)
                
            if r == rows - 1:
                cbar = fig.colorbar(im_err, ax=ax, orientation='horizontal', fraction=0.05, pad=0.05)
                cbar.set_label('Error (dex)', fontsize=16)
                cbar.ax.tick_params(labelsize=12)
                cbar.locator = ticker.MaxNLocator(nbins=4)
                cbar.update_ticks()

        current_highlight = get_highlight_col(r)

        # --- DYNAMIC HIGHLIGHT LOGIC ---
        if current_highlight is not None and col_idx == current_highlight:
            # Add a thick green border
            for spine in ax.spines.values():
                spine.set_edgecolor(highlight_color)
                spine.set_linewidth(4)
                spine.set_visible(True)
            
            # Optional: Add an overlay rectangle for extra emphasis
            # rect = patches.Rectangle((0, 0), 1, 1, linewidth=0, edgecolor='none',
            #                          facecolor=highlight_color, alpha=0.1, 
            #                          transform=ax.transAxes, zorder=5)
            # ax.add_patch(rect)
        # else:
            # Ensure non-highlighted cells have no visible spines to maintain the grid look
            # for spine in ax.spines.values():
                # spine.set_visible(False)

        ax.set_xticks([])
        ax.set_yticks([])

# plt.tight_layout()
plt.savefig(os.path.join(savedir, f'1_inference_maps_stride_{stride}_{dataset_size}.pdf'), bbox_inches='tight')
plt.close()

# ==========================================
# PLOT 2: HEIGHT-COLOR-CODED SCATTER
# ==========================================
print("Generating Plot 2: Height-Color-Coded Scatter...")
fig_scatter, axes_scatter = plt.subplots(3, 2, figsize=(10, 13), dpi=150, sharex=True, sharey=True, gridspec_kw={'hspace': 0.03, 'wspace': 0.03})
axes_scatter = axes_scatter.flatten()
last_scatter = None

for i in range(nlev):
    ax = axes_scatter[i]
    # randomly sample 100k points for plotting to avoid overcrowding
    # if len(targets_denorm_flat) > 500000:
    #     sample_indices = np.random.choice(len(targets_denorm_flat), size=500000, replace=False)
    #     x = targets_denorm_flat[sample_indices, i]
    #     y = predictions_denorm_flat[sample_indices, i]
    #     z_colors = z_grid_flat[sample_indices]
    # else:
    x = targets_denorm_flat[:, i]
    y = predictions_denorm_flat[:, i]
    z_colors = z_grid_flat[:]

    if len(x) > 0:
        scatter = ax.scatter(x, y, c=z_colors, cmap='viridis', s=0.75, alpha=0.05, rasterized=True)
        last_scatter = scatter

        pearson_r = np.corrcoef(x, y)[0, 1]
        r_squared = pearson_r ** 2
        
        
        if i == nlev - 1:
                ax.text(0.95, 0.05, r'$Ca_{III}$'+f': $R^2 = {r_squared:.5f}$', 
                        transform=ax.transAxes, fontsize=14, horizontalalignment='right', 
                        verticalalignment='bottom', bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="gray", alpha=0.8))
        else:
            ax.text(0.95, 0.05, r'$Ca_{II}$'+f'(i={i}): $R^2 = {r_squared:.5f}$', 
                    transform=ax.transAxes, fontsize=14, horizontalalignment='right', 
                    verticalalignment='bottom', bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="gray", alpha=0.8))
        
        lims = [np.min([x, y]), np.max([x, y])]
        ax.plot(lims, lims, 'r--', alpha=0.75, zorder=1, label='y=x')
        ax.set_xscale('log')
        ax.set_yscale('log')

    if i in [4, 5]:
        ax.set_xlabel('Original', fontsize=18)
    if i in [0, 2, 4]:
        ax.set_ylabel('Predicted', fontsize=18)
    if i in [0]:
        ax.legend(loc='upper left', fontsize=14)
    ax.tick_params(labelsize=14)

if last_scatter is not None:
    cbar = fig_scatter.colorbar(last_scatter, ax=axes_scatter.ravel().tolist(), pad=0.02, aspect=60, shrink=0.95)
    cbar.set_label('Height [Mm]', fontsize=18)
    cbar.ax.tick_params(labelsize=14)
    cbar.solids.set(alpha=1)

# plt.tight_layout()
plt.savefig(os.path.join(savedir, f'3_inference_scatter_height_stride_{stride}_{dataset_size}.pdf'), bbox_inches='tight')
plt.close()

# ==========================================
# PLOT 3: HEIGHT-COLOR-CODED ANALYSIS
# ==========================================
print("Generating Plot 3: Height-Color-Coded Analysis...")
fig_comp, axes_comp = plt.subplots(nlev, 2, figsize=(10, 13), dpi=150, sharex='col', 
                                   gridspec_kw={'hspace': 0.15, 'wspace': 0.1})

height_groups = {
    f'Bottom (z < 2) Mm': (z_indices_flat < 25),
    f'Middle (2 < z < 4) Mm': (z_indices_flat >= 25) & (z_indices_flat < 37),
    f'Top (z >= 4) Mm': (z_indices_flat >= 37)
}
colors_list = ['blue', 'green', 'red']

for i in range(nlev):
    # --- Column 1: Residuals ---
    ax1 = axes_comp[i, 0]
    all_residuals = residuals_denorm[:, i] * 100
    lower, upper = -50, 50 
    
    for color, (label, mask) in zip(colors_list, height_groups.items()):
        data = all_residuals[mask]
        ax1.hist(data, bins=100, range=(lower, upper), density=True, alpha=0.5, label=label, color=color)

    ax1.axvline(0, color='k', linestyle='--')
    if i == 0: ax1.set_title(f'Residuals (Original)', fontsize=16)
    if i == nlev-1: ax1.set_xlabel('Relative Error (%)', fontsize=16)
    
    ax1.set_ylabel(r'$Ca_{II}$'+f' (i={i})', fontsize=16)
    if i == nlev - 1:
        ax1.set_ylabel(r'$Ca_{III}$', fontsize=16)
    # ax1.grid(True, linestyle='--', alpha=0.5)

    # --- Column 2: Distributions ---
    ax2 = axes_comp[i, 1]
    valid_mask = (targets_denorm_flat[:, i] > 0)
    
    if np.any(valid_mask):
        bins = np.logspace(np.log10(targets_denorm_flat[valid_mask, i].min()), 
                           np.log10(targets_denorm_flat[:, i].max()), 75)
        
        for color, (label, mask) in zip(colors_list, height_groups.items()):
            ax2.hist(targets_denorm_flat[valid_mask & mask, i], bins=bins, 
                     alpha=0.6, label=f'Actual ({label})', 
                     histtype='step', linewidth=2, color=color)
            ax2.hist(predictions_denorm_flat[valid_mask & mask, i], bins=bins,  label=f'Predicted ({label})',
                     alpha=0.6, histtype='stepfilled', hatch='//', edgecolor=color, facecolor='none')

    if i == 0: ax2.set_title(f'Population Distribution', fontsize=16)
    if i == nlev-1: ax2.set_xlabel('Population', fontsize=16)
    
    ax2.set_xscale('log')
    # ax2.grid(True, linestyle='--', alpha=0.5)
    ax2.ticklabel_format(axis='y', style='sci', scilimits=(0,0), useMathText=True)
    ax2.locator_params(axis='y', nbins=5)
    
    # Legend on first row only
    if i == 0:
        ax1.legend(framealpha=0.5, facecolor='white', loc='upper right', fontsize=12)
        # ax2.legend(framealpha=0.5, facecolor='white', loc='upper right', fontsize=8)

# plt.tight_layout()
plt.savefig(os.path.join(savedir, f'4_inference_errors_hist_height_stride_{stride}_{dataset_size}.pdf'), bbox_inches='tight')
plt.close()

print(f"All done! Plots saved to {savedir}")